local hankaku = require("daihon.hankaku")

test("半角：行の頭の ／／ ＃ （ ￥ は半角に", function()
  eq("/", hankaku.convert("／", ""))
  eq("/", hankaku.convert("／", "/"))
  eq("/", hankaku.convert("／", "  /"))
  eq("#", hankaku.convert("＃", ""))
  eq("#", hankaku.convert("＃", "#"))
  eq("(", hankaku.convert("（", ""))
  eq(")", hankaku.convert("）", "(夜"))
  eq(nil, hankaku.convert("）", "あ（い"))
  eq("¥", hankaku.convert("￥", ""))
end)

test("半角：セリフの中の全角はそのまま", function()
  eq(nil, hankaku.convert("／", "AかB"))
  eq(nil, hankaku.convert("（", "あ"))
  eq(nil, hankaku.convert("：", "妹"))
  eq(nil, hankaku.convert("：", "// ▼前"))
  eq(nil, hankaku.convert("あ", ""))
end)

test("半角：塊のかっこはどこでも、SE のあとの ： と、記号のあとの全角の空白", function()
  eq("{", hankaku.convert("｛", "そして"))
  eq("}", hankaku.convert("｝", "{いつもの"))
  eq(":", hankaku.convert("：", "// SE"))
  eq(":", hankaku.convert("：", "// SE "))
  eq(" ", hankaku.convert("\227\128\128", "##"))
  eq(" ", hankaku.convert("\227\128\128", "//"))
  eq(nil, hankaku.convert("\227\128\128", "おかえり"))
end)
