name: test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim: [v0.10.4, stable]
    steps:
      - uses: actions/checkout@v7
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim }}
      - run: nvim --headless -l tests/run.lua

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.5.2
          args: --check lua plugin tests
